/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { EventDataChild, itemTreeModel } from "./components/wiz-tree/wiz-tree-models";
export namespace Components {
    interface WizTree {
        "fetchdata": boolean;
        "list": itemTreeModel[];
        "setchild": EventDataChild;
    }
}
declare global {
    interface HTMLWizTreeElement extends Components.WizTree, HTMLStencilElement {
    }
    var HTMLWizTreeElement: {
        prototype: HTMLWizTreeElement;
        new (): HTMLWizTreeElement;
    };
    interface HTMLElementTagNameMap {
        "wiz-tree": HTMLWizTreeElement;
    }
}
declare namespace LocalJSX {
    interface WizTree {
        "fetchdata"?: boolean;
        "list"?: itemTreeModel[];
        "onHandleSelected"?: (event: CustomEvent<{data: any, label: string | number}[]>) => void;
        "onRequestData"?: (event: CustomEvent<EventDataChild>) => void;
        "setchild"?: EventDataChild;
    }
    interface IntrinsicElements {
        "wiz-tree": WizTree;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wiz-tree": LocalJSX.WizTree & JSXBase.HTMLAttributes<HTMLWizTreeElement>;
        }
    }
}
